### PR TITLE
Add option --enable-all to enable all rules

### PR DESCRIPTION
**Pull request by dvob**
It would be nice to have a way to enable all available rules.
It seems that there are also other people requesting this feature #1056

### CODE REVIEW

**Comment by wata727** [comment]
Thank you for your contribution!
Unfortunately, there are still many things to consider in order to achieve this goal.

First, this change only enables some of the Terraform rules built into the TFLint core, not rules provided by plugins. To enable all plugin rules, you need to add an RPC endpoint to plugin and call it from TFLint core.

Second, we can't enable rules that require settings like `aws_s3_bucket_name` automatically.
https://github.com/terraform-linters/tflint-ruleset-aws/blob/v0.12.0/docs/rules/aws_s3_bucket_name.md

For these reasons, I don't think we should add an option to enable all rules uniformly.
It is a historical reason that Terraform rules are included in the core, and I believe that it is better to cut this out into a ruleset so that it can be controlled in units of rulesets.

**Comment by dvob** [comment]
Hi @wata727 thank you for maintaining tflint.

I was looking for a way to find unused variables in Terraform files and found out that this should be possible with tflint via this issue https://github.com/hashicorp/terraform/issues/11412#issuecomment-624452494
I downloaded tflint but I did not understand why tflint did not report the unused variables. It was not clear to me that only certain rules are enabled by default. Then looked for a way to enable all rules. Whats actually  the reason that not all builtin rules are enabled?

In my opinion it would be nice to have the the most common and provider independent checks built into the TFLlint core. This way using tflint would be super simple. You could download tflint and run it in the directory where you have your Terraform files without further configuration. And then, only if you have unwanted warnings or if you want to add additional checks, you can start to configure tflint to disable rules or add plugins.

For me it would be ok if this option would only enable the built in rules but I understand that this could be confusing for people which use plugins. So I understand if you don't want this change in tflint and its OK if you close this PR.

**Comment by gtirloni** [comment]
I'm just trying tflint on a large project and I was surprised that it did not detect _anything_ wrong. It took me some time to realize that rules were not being enabled at all and I had to specify them one by one (either in the config file or command line). Had I not dug deeper into the issue I would have thought tflint didn't do anything at all.

It might be worth to enable at least all core rules that don't require customization from users.

**Comment by dvob** [comment]
@wata727 Somehow i missed your last reply. 

How do I install the strict rule set?

I think your design decision is perfectly fine. But if you want to solve it like this i suggest that all rules are disabled by default and a warning is presented to the user if no rules are enabled or if no configuration was found.

This way if a user just downloads tflint and expect it to check certain basic rules they get a warning that they have to configure the rules themself. At least for me such a hint would have been very helpful.

**Comment by wata727** [comment]
Thank you for the advice. To be sure, the current UX is not ideal. The biggest problem is that the terraform rules have been built into the core for historical reasons, and I believe that we can improve it to design a better UX.

**Comment by wata727** [comment]
The current design cannot accept this feature and will close it. Thank you for your contribution.

**Pull request closed without merging**
