### PR TITLE
chore(deps): bump go to v1.15

### PR DESCRIPTION
**Pull request by chenrui333**

### CODE REVIEW

**Comment by bendrucker** [comment]
Build is failing:

* `golang:1.15-alpine3.11` is not a valid image
* The generated code is slightly different, so run `make code` to update that

**Comment by chenrui333** [comment]
Thanks @bendrucker!!

**Comment by chenrui333** [comment]
I did keep running into `api-2.json` reference issue, not sure how did you resolve it?

```
$ make code
go generate ./...
panic: open aws-sdk-go/models/apis/acm-pca/2017-08-22/api-2.json: no such file or directory
```

**Comment by bendrucker** [comment]
Perhaps your submodule is out of date? `git submodule update --init` should address that.

**Comment by chenrui333** [comment]
aha, that makes more sense.

**Pull request merged**
