### PR TITLE
Add `Backend()` to plugin server

### PR DESCRIPTION
**Pull request by pd**

### CODE REVIEW

**Comment by pd** [comment]
The failing checks are due to the corresponding tflint-plugin-sdk changes; I suppose those have to land first before this can successfully build.

**Comment by wata727** [comment]
@pd Looks good. I have merged the changes to tflint-plugin-sdk. Can you upgrade the dependency to pass the CI?

**Comment by pd** [comment]
@wata727 Updated the dependency. If you want to add a new tag to the SDK, I can update go.mod here to reference that instead, but this is green now either way.

**Comment by wata727** [comment]
Thanks!

**Pull request merged**
