### PR TITLE
Add --chdir option

### PR DESCRIPTION
**Pull request by wata727**
Fixes https://github.com/terraform-linters/tflint/issues/1315
Fixes https://github.com/terraform-linters/tflint/issues/1508
See also https://github.com/hashicorp/terraform/pull/26087

This PR adds `--chdir` option for inspection. This is intended to match Terraform's behavior regarding other directories.

You can inspect against a Terraform configuration in another directory like this:

```console
$ tflint --chdir=environment/production
```

Similar behavior could be reproduced by passing the directory as an argument, but `--chdir` differs in the following points:

- Load a module manifest file under the directory passed by `--chdir`, not the current directory.
  - This resolves https://github.com/terraform-linters/tflint/issues/1508.
  - It means `terraform -chdir=dir get; tflint --chdir=dir --module` works fine.
- `file("./config.tmpl")` is resolved against the directory passed by `--chdir`, not the current directory.
  - This is the same behavior as Terraform and is preferable in many cases.

For the above reasons, we recommend that users using directory arguments switch to the `--chdir` option. The directory argument still works fine at this point, but is deprecated and may be removed in a future version. To avoid confusion, using `--chdir` option and a directory argument together is an error.

~~The `--chdir` behavior is the same as [Terraform's behavior](https://developer.hashicorp.com/terraform/cli/commands#switching-working-directory-with-chdir), but there are some TFLint-specific considerations:~~

- ~~Config file (`.tflint.hcl`) is processed before acting on the `--chdir` option.~~
- ~~Files specified with relative paths like `--var-file` and `varfile` on config files are resolved against the original working directory.~~

**UPDATED:** The above exceptions were eventually removed. `--chdir` is basically equivalent to `cd dir; tflint`.

However, unlike Terraform, `--chdir` cannot be used with `tflint --init` or `tflint --langserver`. This is because I believe that `--chdir` is necessary only in limited cases.

In the future, this behavior is intended to be used for [recursive inspection](https://github.com/terraform-linters/tflint/issues/1355). Recursive inspection is equivalent to running `--chdir` for each module and returning the results.

## ToDo

- [x] Add tests
- [x] Add E2E tests
- [x] Add documentation
- [x] Define behavior when `--chdir` and directory argument are passed
- [x] Return an error if `--chdir` is passed outside of inspection

### CODE REVIEW

**Comment by wata727** [comment]
@bendrucker Could you give me your opinion on the behavior?

**Review by bendrucker — COMMENTED** [review]
I'd expect this behavior to work exactly like `terraform -chdir`, meaning the `chdir` call happens before anything else, and is equivalent to `cd dir/ && tflint`. I'm assuming the difference comes down to the intent to use the internals in the future for recursive inspection. But I think that implementation detail should be hidden and the flag should match Terraform's behavior.

As is, users can use a shared plugin dir (which is the default?) and an absolute path to config for recursion:


```sh
config=$(realpath .tflint.hcl)
for mod in mod1 mod2; do
  tflint --chdir $mod --config $config
done
```

Not clear to me why there should be exceptions for varfiles either. If you want to share, you can use a similar pattern. Future recursive inspection could essentially do this internally, passing an absolute path for the config and var files down so that the directory can be changed. These files don't contain any relative paths of their own. 

I think we should be preparing to move `init` and `languageserver` to commands, with a compatibility later to to transform the existing args format. Probably `version` and `as-plugin` as well. These aren't options that modify behavior in the traditional sense. They do something so substantially different that they deserve their own sub-command. Ideally `--chdir` should support all commands, including `init`.

In a world with subcommands, `--chdir` could exactly match Terraform, which requires global flags to be passed before subcommands:

```sh
terraform -chdir=mod1 init
terraform -chdir=mod1 validate -json
```

```sh
tflint --chdir=mod1 init
tflint --chdir=mod1 inspect --format json
```

Happy to do a pass on the code as well once we discuss the behavior.

**Comment by wata727** [comment]
Thank you for the feedback!

Agreed that the flag should match Terraform's behavior. As you say, one of the main reasons for the first exception is for recursive inspection. You might find this behavior counter-intuitive for the `-chdir` option, but I believe this makes sense since [the `terraform.rc` file already ignores `-chdir`](https://developer.hashicorp.com/terraform/cli/commands#switching-working-directory-with-chdir).

For the second exception, I didn't want the following case to be an error:

```console
$ tflint --chdir=dir --var-file=dir/varfile.tfvars
```

When entering the path for `--var-file`, I think it is intuitive to specify the path relative to the original working directory.

> I think we should be preparing to move init and languageserver to commands, with a compatibility later to to transform the existing args format. Probably version and as-plugin as well.

Yes. I think so too. However, I would like `tflint` without subcommands to behave as same as `tflint inspect`. I think it is necessary to investigate whether this can be satisfied.

**Comment by bendrucker** [comment]
I think we'll manage to find ways to preserve backwards compatibility for arguments. The "command not found" handler could call `inspect` with the given args, for example. 

Re `.terraformrc`, I assume you're referring to this:

> Settings in the [CLI Configuration](https://developer.hashicorp.com/terraform/cli/config/config-file) are not for a specific subcommand and Terraform processes them before acting on the -chdir option.

Typically, this file is in `$HOME` and shouldn't contain any relative paths. I'm not even sure whether relative paths would be handled relative to the config file or the cwd. 

Seems like the only time this has any visible impact on normal use-cases is this:

> If a terraform.d/plugins directory exists in the current working directory then Terraform will also include that directory, regardless of your operating system. This behavior changes when you use the -chdir option with the init command. In that case, Terraform checks for the terraform.d/plugins directory in the launch directory and not in the directory you specified with -chdir.

https://developer.hashicorp.com/terraform/cli/config/config-file#provider_installation

In keeping with Terraform behavior, I'd expect var files to be loaded after changing directory, since var files are generally part of the configuration.

Given the following file tree:

```
.
└── mod
    ├── main.tf
    └── vars.tfvars
```

This is the behavior:

```sh
$ terraform -chdir=mod apply -var-file=vars.tfvars

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are needed.

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

/var/folders/m6/7nt7y_s54lsbrwsjb_xsmx7m0000gn/T/varfile
$ terraform -chdir=mod apply -var-file=mod/vars.tfvars
╷
│ Error: Failed to read variables file
│
│ Given variables file mod/vars.tfvars does not exist.
╵
```

**Comment by wata727** [comment]
Finally, I decided to load the config file in the changed directory. Fixed https://github.com/terraform-linters/tflint/pull/1612/commits/a2b6654abf8896e38652ffe1eb8c669bdc36407e

I've tried thinking about why it loads the config file in the original working directory, but I haven't found a reasonable reason. The plugin process working directory issue will be resolved by allowing plugins to refer to the original working directory.

If there are no problems, I plan to merge this PR within a few days.

**Comment by bendrucker** [comment]
Will review the latest comments and give this a try today

**Pull request merged**
