### PR TITLE
Rule for checking missing braces for variable references (#436)

### PR DESCRIPTION
**Pull request by abitrolly**
The following template reference is invalid, is treated as
a literal string and not expanded.

    resource "null_resource" "generate_inventory" {
      triggers = {
        template_rendered = "$data.template_file.inventory_template.rendered"
      }
    ...

### CODE REVIEW

**Comment by bendrucker** [comment]
Hi there:

* This style of interpolation is deprecated in Terraform 0.12
* It's going to be fairly difficult to avoid false positives

We've added some methods to the runner recently that would help with rules like this. If you're interested in pursuing further happy to discuss how viable possible approaches might be.

**Comment by abitrolly** [comment]
So what is the 0.12 alternative?

**Comment by bendrucker** [comment]
0.12 will print a warning for "${data.template_file.inventory_template.rendered}" and Terraform 0.13  will error. TFLint can enforce this for you now:

https://github.com/terraform-linters/tflint/blob/master/docs/rules/terraform_deprecated_interpolation.md

The quotes and interpolation is unnecessary, simply `data.template_file.inventory_template.rendered` will do. 

This problem obviously still exists if you do this:

```
"foo-$data.template_file.inventory_template.rendered"
```

However, I'll warn you that the difficulty of detecting this accurately is pretty high.

**Comment by abitrolly** [comment]
It evolves faster than me. )

**Pull request closed without merging**
