### PR TITLE
I18n/es

### PR DESCRIPTION
**Pull request by BreakingPitt**
This PR adds a complete Spanish version of the TFLint documentation. It has been added to the docs/es directory.

Maybe this could help to add more l18n languages to this project.

### CODE REVIEW

**Comment by bendrucker** [comment]
Thanks! Pedro reached out via email and I told him we could include this along with instructions that translations are "best effort" and over time may become out of date. Will review this soon.

**Comment by wata727** [comment]
In my opinion, outdated documentation can confuse users and is negative about i18n.
It's a good idea to start i18n as a separate project unrelated to this organization.

**Comment by BreakingPitt** [comment]
Hi Kazuma:

The goal is continue maintaining a updated version of the localized documentation, not make an initial pull request and let the translation outdated.

Anyway, any help about what could be the best way to work on this is highly appreciated… I’ve spent a lot of time and effort doing this work.

Best regards, Pedro

**Comment by wata727** [comment]
Hmmm, but unfortunately I'm not fluent in Spanish so I can't update the translated document when I make a major feature change. Therefore, it is not possible to review whether the updated translation is appropriate. This is one of the negative reasons for i18n. Ideally, documents should be available in many languages, but there is a lack of maintainers for that.

If @bendrucker is positive about this change, I wouldn't strongly oppose this pull request. However, keep in mind that i18n may be removed if we determine that they have been delayed for a long time.

Finally, thank you for taking the time to do this. I agree that such contributions are valuable for increasing the number of users.

**Comment by BreakingPitt** [comment]
Hey... I would like to continue translating the new updates made to the documentation, maybe if we found a way to notify that there are documentation changes I can keep it up to date without effort.

Best regards

**Comment by PatMyron** [comment]
agree with @wata727: https://github.com/aws-cloudformation/cfn-lint/issues/192#issuecomment-574302878

Are there specific parts of the documentation that particularly don't translate well with tooling like automatic browser translation? Perhaps we can focus on simplifying the english docs to be more accessible

**Comment by bendrucker** [comment]
I'm semi-proficient in Spanish and can read/edit but would struggle to do technical writing from scratch. Since Pedro's done all this work already I wanted to find a place to feature it but share the already expressed concerns about keeping documentation up to date.

On second thought if we wanted to keep this in the org we'd probably make a dedicated repo for translations. Don't worry about that for now, I can move this PR there if that's what we decide. A second repo more clearly expresses the expectation that updates will be asynchronous. We might also just ask you to host this in your own repo and link there.

As far as detecting updates goes, you can watch the main repo. That'll be a bit noisy. You could potentially just watch releases. We could also in theory detect changes to `docs/` and issue notifications via Actions, but I can't commit to working on those workflows. If you feel you can keep up with updates, at least on each release, we could trial this for a while and see if it's sustainable.

**Comment by BreakingPitt** [comment]
> agree with @wata727: [aws-cloudformation/cfn-lint#192 (comment)](https://github.com/aws-cloudformation/cfn-lint/issues/192#issuecomment-574302878)
> 
> Are there specific parts of the documentation that particularly don't translate well with tooling like automatic browser translation? Perhaps we can focus on simplifying the english docs to be more accessible

Base on my personal experince, automatic translations are not very correct, at least into Spanish language. After years of working with software translation tools, it's better not to use them.

**Comment by BreakingPitt** [comment]
> I'm semi-proficient in Spanish and can read/edit but would struggle to do technical writing from scratch. Since Pedro's done all this work already I wanted to find a place to feature it but share the already expressed concerns about keeping documentation up to date.
> 
> On second thought if we wanted to keep this in the org we'd probably make a dedicated repo for translations. Don't worry about that for now, I can move this PR there if that's what we decide. A second repo more clearly expresses the expectation that updates will be asynchronous. We might also just ask you to host this in your own repo and link there.
> 
> As far as detecting updates goes, you can watch the main repo. That'll be a bit noisy. You could potentially just watch releases. We could also in theory detect changes to `docs/` and issue notifications via Actions, but I can't commit to working on those workflows. If you feel you can keep up with updates, at least on each release, we could trial this for a while and see if it's sustainable.

As @bendrucker states here and if finally everyones agree, the first step would be to decide where we want to put all this work.

**Comment by wata727** [comment]
I would like to respect your thought. You can merge this pull request or create a second repository. Personally, I recommend starting as your personal repository like capybara-readme-ja.
https://github.com/willnet/capybara-readme-ja

**Comment by BreakingPitt** [comment]
Hey, as suggested I will close this pull request and let this on a personal repo.

Thanks!

**Comment by bendrucker** [comment]
Let us know when you have that up. We can add links.

**Pull request closed without merging**
