### PR TITLE
build: Remove some os/arch build targets

### PR DESCRIPTION
**Pull request by wata727**
Fixes https://github.com/terraform-linters/tflint/issues/1219

### CODE REVIEW

**Comment by wata727** [comment]
Umm... `goreleaser build` still takes about 10min...

**Comment by wata727** [comment]
CI takes too long, so I decided not to build for each platform in PR build.

**Review by chenrui333 — COMMENTED** [review]
👍

**Comment by chenrui333** [comment]
This looks like a potential improvement opportunity of parallelizing the goreleaser builds 😂

**Pull request merged**
