### PR TITLE
serif: fix incorrect `endLine`

### PR DESCRIPTION
**Pull request by tbutler-qontigo**
Looks like https://github.com/terraform-linters/tflint/pull/1686/files accidentlly changed the End.Line to Start.Column

### CODE REVIEW

**Review by bendrucker — CHANGES_REQUESTED** [review]
This needs test coverage

**Comment by tbutler-qontigo** [comment]
> This needs test coverage

Apologies, added.  Not a GO programmer by trade, but your existing test suite made it easy to add more tests - added for both single and mult-line issues.

**Review by bendrucker — APPROVED** [review]
Thank you!

**Comment by tbutler-qontigo** [comment]
My pleasure - now when do we get a v0.46.1 release? ;)

**Comment by wata727** [comment]
Released
https://github.com/terraform-linters/tflint/releases/tag/v0.46.1

**Pull request merged**
